[phases.install]
cmds = [
    "python -m venv /app/.venv",
    ". /app/.venv/bin/activate",
    "git config --global url.\"https://${GITHUB_TOKEN}:x-oauth-basic@github.com/\".insteadOf \"https://github.com/\"",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = []
