[build]
builder = "RAILPACK"

[build.env]
GIT_CONFIG_COUNT = "1"
GIT_CONFIG_KEY_0 = "url.https://$GITHUB_TOKEN@github.com/.insteadOf"
GIT_CONFIG_VALUE_0 = "https://github.com/"

[deploy]
startCommand = "poetry run uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
